const ActionTypes = {
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_DOCTOR_NAME: 'CHANGE_DOCTOR_NAME',
  CHANGE_SPECIALTIES: 'CHANGE_SPECIALTIES',
  CHANGE_RESULTS: 'CHANGE_RESULTS',
  CHANGE_IS_FETCHING: 'CHANGE_IS_FETCHING'
};

const PageConstants = {
  INTRO: 'INTRO',
  DOCTOR: 'DOCTOR',
  SPECIALTIES: 'SPECIALTIES',
  RESULTS: 'RESULTS'
};

export { ActionTypes, PageConstants };
